### ISSUE TITLE
Dead tutorial link

### ISSUE THREAD

**Issue by Helmoes** [NicklasVraa/Draw-io-ECE#3]
Hey, I noticed the link to the tutorial at the end is dead.
Here's the working one: https://www.drawio.com/doc/faq/shape-complex-create-edit

**Comment by NicklasVraa** [comment]
Thanks, appreciate it :)

**Comment by Helmoes** [comment]
Np! Btw, would you please be willing to share your `.drawio` files for the op amp and analog filter examples in `meta/examples`? That would save me quite some time. :)
