### ISSUE TITLE
Customize draw io UI

### ISSUE THREAD

**Issue by frazik-main** [NicklasVraa/Draw-io-ECE#5]
Can you share how did you customize draw io to look like this:
https://github.com/NicklasVraa/Draw-io-ECE/blob/master/meta/dark_mode.png
?

Thanks for great resource!

**Comment by NicklasVraa** [comment]
That particular image shows the default dark mode. You can find it under settings/appearence or something similar sounding. Depending on your version, there may be a sun/moon icon that you can click.

Glad you find it useful :)
